### PR TITLE
Fix matching %h placeholders

### LINKED ISSUE #10: Placeholder in sshconfig interpreted literally
Behavior:
```
 $ sex -H "demo-1.adjust.com" Adjust:Spipe:setup
[2019-01-24 09:45:27] WARN - This is development release 1.6.0.3 of (S)!ex. Feature checks are disabled for 1.4 until done right.
[2019-01-24 09:45:28] <local> INFO - Running task Adjust:Spipe:setup on demo-1.adjust.com
[2019-01-24 09:45:28] demo-1.adjust.com WARN - Can't authenticate against %h (unable to establish master SSH connection: master process exited unexpectedly)
[2019-01-24 09:45:29] <local> ERROR - 1 out of 1 task(s) failed:
[2019-01-24 09:45:29] <local> ERROR - 	Adjust:Spipe:setup failed on demo-1.adjust.com
[2019-01-24 09:45:29] <local> ERROR - 		Couldn't authenticate against demo-1.adjust.com. It may be caused by one or more of:
[2019-01-24 09:45:29] <local> ERROR - 		 - wrong username, password, key or passphrase
[2019-01-24 09:45:29] <local> ERROR - 		 - changed remote host key
[2019-01-24 09:45:29] <local> ERROR - 		 - root is not permitted to login over SSH
[2019-01-24 09:45:29] <local> ERROR - 		 at /usr/lib64/perl5/vendor_perl/5.26.2/Rex/TaskList/Base.pm line 342.
```

`~/.ssh/config`:
```
Host	demo-1.adjust.com
	Hostname	%h
	User		root
	Port		22
	IdentityFile	~/.ssh/id_rsa
```

Usually `%h` is used to pass matched wildcards to `Hostname`. In this case a single static host seems to give something trouble. A wildcard rule works properly.

### PR DESCRIPTION
**Pull request by amaxine**
Fixes #10.

### CODE REVIEW

File: lib/Rex/Config.pm [hunk 1]
```diff
@@ -682,6 +682,9 @@ sub get_ssh_config_hostname {
     if ( $SSH_CONFIG_FOR{ $param->{server} }->{hostname} =~ m/^\%h\.(.*)/ ) {
       return $param->{server} . "." . $1;
     }
+    elsif ( $SSH_CONFIG_FOR{ $param->{server} }->{hostname} =~ m/^\%h$/ ) {
```
Comment (matt604-adjust) [inline lib/Rex/Config.pm]: THis works. This could be a literal match to "%h". Heck, you could match this line OR "%h". -- m!

Comment (amaxine) [reply lib/Rex/Config.pm]: Overengineering is the name of the game (or in this case, copy pasting the previous regex instead of thinking about things for 2s). Will simplify and then merge, ta! :)

Comment (alip) [reply lib/Rex/Config.pm]: Speaking about overengineering, you could also have a single if clause with the regex `^\%h(\.(.*))?$` and append `$1` without the additional dot. I'm fine either way.

Could you be so kind to submit this to [RexOps/Rex](https://github.com/RexOps/Rex) as well? This is potentially useful for others as well.

Comment (amaxine) [reply lib/Rex/Config.pm]: Thank you, that's a better idea. I'll look after upstreaming after we merge it here
